# docker-compose.yml
version: "3.8"

services:
  yii2:
    image: vinayvasantham/yii2-app:latest
    ports:
      - "9000:9000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        failure_action: rollback
    networks:
      - yii2-net

networks:
  yii2-net:

