name: CI/CD Deploy to EC2

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: vinayvasantham/yii2-app:latest
  CONTAINER_PORT: 9000

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}:latest

    - name: Decode and write SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" | base64 -d > ec2_key.pem
        chmod 600 ec2_key.pem

    - name: Deploy to EC2 via SSH
      run: |
        ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          docker pull ${{ env.IMAGE_NAME }}:latest
          docker service update --image ${{ env.IMAGE_NAME }}:latest yii2_app_yii2 || echo "Update failed. Rolling back..."docker service rollback yii2_app_yii2)
        EOF
